# Generated by Django 3.1.6 on 2021-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('option', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('duree', models.TimeField()),
                ('photo', models.URLField()),
                ('prix', models.IntegerField()),
                ('description', models.TextField()),
                ('excursion', models.ManyToManyField(blank=True, related_name='excursion', to='projets.Excursion')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=500)),
                ('voyage', models.ManyToManyField(blank=True, related_name='voyage', to='projets.Voyage')),
            ],
        ),
    ]
